#!/usr/bin/env bash

# # work=`echo "$HOME/go/src $HOME/cloned $HOME/work" | tr ' ' '\n'`
# # personal=`echo "$HOME/personal" | tr ' ' '\n'`
# work=`echo "$HOME/go/src $HOME/cloned $HOME/work"`
# personal=`echo "$HOME/personal"`

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(
        { 
            find "$HOME/go/src" -type d -name .git -prune -exec dirname {} \; ;
            find "$HOME/cloned" "$HOME/personal" "$HOME/personal/go" "$HOME/work" -type d -maxdepth 1 -mindepth 1 ;
            printf "%s\n" "$HOME/.dotfiles" ;
        } | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux -u new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux -u new-session -ds $selected_name -c $selected
fi

if [[ -z $TMUX ]]; then
    tmux -u attach -t $selected_name
else
    tmux -u switch-client -t $selected_name
fi

