#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(tmux ls | fzf | sed -e "s/:.*//")
fi

if [[ -z $selected ]]; then
    exit 0
fi

echo "attaching to $selected"
if [[ -z $TMUX ]]; then
    tmux -u attach -t $selected
else
    tmux -u switch-client -t $selected
fi
