#!/usr/bin/env bash
set -e

_envs=(
    # Display
    WAYLAND_DISPLAY
    DISPLAY
    # xdg
    USERNAME
    XDG_BACKEND
    XDG_CURRENT_DESKTOP
    XDG_SESSION_TYPE
    XDG_SESSION_ID
    XDG_SESSION_CLASS
    XDG_SESSION_DESKTOP
    XDG_SEAT
    XDG_VTNR
    # hyprland
    HYPRLAND_CMD
    HYPRLAND_INSTANCE_SIGNATURE
    # misc
    XCURSOR_SIZE
    # ssh
    SSH_AUTH_SOCK
)

case "$1" in
system)
    dbus-update-activation-environment --systemd "${_envs[@]}"
    ;;
tmux)
    for v in "${_envs[@]}"; do
        if [[ -n ${!v} ]]; then
            tmux set-env -g "$v" "${!v}"
        fi
    done
    ;;
*)
    echo "operation required"
esac
